# phpRack
#
# This source file is subject to the new BSD license that is bundled
# with this package in the file LICENSE.txt. It is also available
# through the world-wide-web at this URL: http://www.phprack.com/LICENSE.txt
# If you did not receive a copy of the license and are unable to
# obtain it through the world-wide-web, please send an email
# to license@phprack.com so we can send you a copy immediately.
#
# SPDX-FileCopyrightText: Copyright (c) 2009-2026, phpRack.com, Inc.
# SPDX-License-Identifier: MIT

errors:
  - yegor256@gmail.com
# alerts:
#   github:
#     - yegor256

tags:
  - pdd
  - bug
