architect:
- yegor256
- davvd
install: |
  sudo pecl install xdebug
  echo "zend_extension=xdebug.so" > xdebug.ini
  sudo mv xdebug.ini /etc/php5/cli/conf.d
  composer install
  sudo npm install jscoverage -g
merge:
  script: |
    ./vendor/phing/phing/bin/phing
  commanders:
  - yegor256
deploy:
  script: |
    ./vendor/phing/phing/bin/phing
  commanders:
  - yegor256
release:
  script: |
    ./vendor/phing/phing/bin/phing main doc
    mkdir build/ftp-upload
    cp phpRack/* build/ftp-upload
    cp src/test/integration-test/* build/ftp-upload
    cp phprack.com/* build/ftp-upload/public
    cp src/phpRack/layout/logo.png build/ftp-upload/public
    cp src/LICENSE.txt build/ftp-upload/public
    cp build/apidocs build/ftp-upload/public/api
    cp build/coverage build/ftp-upload/public/coverage
    # upload by ftp
  commanders:
  - yegor256