<!DOCTYPE html PUBLIC
    "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
 * @version $Id: index.phtml 260 2010-04-01 05:37:36Z yegor256@yahoo.com $
-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
            <?php include PHPRACK_PATH . '/layout/index.css' ?>
        </style>
        <title>phpRack Testing Report</title>
    </head>

    <body>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>

        <div id='logo'>
            <a href='http://www.phprack.com'><img
                src='data:image/png;base64,<?php
                    echo base64_encode(
                        file_get_contents(PHPRACK_PATH . '/layout/logo.png')
                    )
                ?>'
                alt='phpRack' /></a>
            <span>v<?php echo PHPRACK_VERSION?></span>
        </div>

        <!-- script content, ZCA-friendly include -->
        <?php eval("include PHPRACK_PATH . '/layout/{$this->script}';")?>
    </body>
</html>
