<!DOCTYPE html PUBLIC
    "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
 *
 * phpRack: Integration Testing Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt. It is also available 
 * through the world-wide-web at this URL: http://www.phprack.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@phprack.com so we can send you a copy immediately.
 *
 * @copyright Copyright (c) phpRack.com
 * @version $Id: index.phtml 286 2010-04-05 13:46:54Z yegor256@yahoo.com $
 * @author netcoderpl@gmail.com
 * @category phpRack
-->

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css"><?php echo $this->compressedCss('index.css') ?></style>
        <title>phpRack Testing Report</title>
    </head>

    <body>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>

        <div id='logo'>
            <a href='http://www.phprack.com'><img
                src='data:image/png;base64,<?php
                    echo base64_encode(
                        file_get_contents(PHPRACK_PATH . '/layout/logo.png')
                    )
                ?>'
                alt='phpRack' /></a>
            <span>v<?php echo PHPRACK_VERSION?></span>
        </div>

        <!-- script content, ZCA-friendly include -->
        <?php eval("include PHPRACK_PATH . '/layout/{$this->script}';")?>
    </body>
</html>
