<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
 * @version $Id: index.phtml 106 2010-03-17 18:05:39Z yegor256@yahoo.com $
-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <body>
        <p><?php echo $this->authResult->getMessage()?></p>
        <form method="post">
            <dd>login: <input name="<?php echo phpRack_Runner::POST_LOGIN?>" /></dd>
            <dd>password: <input name="<?php echo phpRack_Runner::POST_PWD?>" type="password" /></dd>
            <dd><input type="submit" /></dd>
        </form>
    </body>
</html>
