<!--
 *
 * SPDX-FileCopyrightText: Copyright (c) 2009-2026 Yegor Bugayenko
 * SPDX-License-Identifier: MIT
 *
 * @author netcoderpl@gmail.com
 * @category phpRack
-->

<p>
    PHPRACK_PATH: <tt><?php echo PHPRACK_PATH?></tt>
    at <?php echo $_SERVER['SERVER_ADDR']?>
</p>

<?php $i = 0; ?>
<?php $jsCalls = array(); ?>
<div id="task-list">
    <?php foreach ($this->runner->getTests() as $test):?>
        <?php $ajaxOptions = $test->getAjaxOptions();?>

        <div id="d<?php echo ++$i?>" class="task">
            <span class="label" title="click to re-start"><?php echo $test->getLabel() ?>:</span>&#160;
            <span class="result" title="click to see the log"><?php
            if (!empty($ajaxOptions['autoStart'])) {
                echo 'waiting...';
            } else {
                echo 'click to start...';
            }
            // No enter before span to avoid slideToggle() problem in IE
            ?></span>
            <span class="tags"></span>
            <pre style="display:none;"></pre>
        </div>
        <?php
        $jsCalls[$i] = array(
            'divId'              => 'div#d' . $i,
            'label'              => $this->jsPath($test->getLabel()),
            'autoStart'          => !empty($ajaxOptions['autoStart']) && !defined('INSTRUMENTED') ? true : false,
            'pauseWhenFocusLost' => !empty($ajaxOptions['pauseWhenFocusLost']) ? true : false,
            'data'               => !empty($ajaxOptions['data']) ? $ajaxOptions['data'] : new stdClass,
            'suiteTest'          => $test instanceof PhpRack_Suite_Test ? true : false
        );
        ?>
    <?php
    endforeach; ?>
</div>

<script type="text/javascript">
//<![CDATA[
    // array with server side params which will be used in javascript
    var phpParams = {
        calls: <?php echo json_encode($jsCalls) ?>,
        ok: '<?php echo phpRack_Test::OK?>',
        failure: '<?php echo phpRack_Test::FAILURE?>',
        requestUri: '<?php echo $_SERVER['REQUEST_URI']?>',
        ajaxTag: '<?php echo PHPRACK_AJAX_TAG?>',
        ajaxToken: '<?php echo PHPRACK_AJAX_TOKEN?>',
    };
    <?php
    if (defined('INSTRUMENTED')) {
        include INSTRUMENTED . '/index.js';
    } else {
        include PHPRACK_PATH . '/layout/js/index.js';
    }
    ?>
//]]>
</script>
