<?php echo "<?xml version=\"1.0\"?>\n" ?>
<!DOCTYPE html PUBLIC
    "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
 *
 * SPDX-FileCopyrightText: Copyright (c) 2009-2026 Yegor Bugayenko
 * SPDX-License-Identifier: MIT
 *
 * @version $Id: index.phtml 286 2010-04-05 13:46:54Z yegor256@yahoo.com $
 * @author netcoderpl@gmail.com
 * @category phpRack
-->

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8"/>
        <style type="text/css"><?php echo $this->compressedCss('index.css') ?></style>
        <title>phpRack Testing Report</title>
    </head>

    <body>
        <script type="text/javascript">
        //<![CDATA[
            <?php include PHPRACK_PATH . '/layout/js/jquery-1.11.2.min.js' ?>
        //]]>
        </script>
        <div id='logo'>
            <a href='http://www.phprack.com'><img
                src='data:image/png;base64,<?php
                    echo base64_encode(
                        file_get_contents(PHPRACK_PATH . '/layout/logo.png')
                    )
                ?>'
                alt='phpRack' /></a>
            <span>v<?php echo PHPRACK_VERSION?></span>
        </div>

        <!-- script content, ZCA-friendly include -->
        <?php eval("include PHPRACK_PATH . '/layout/{$this->script}';")?>
    </body>
</html>
