<!--
 *
 * AAAAA
 *
 * @version $Id: index.phtml 286 2010-04-05 13:46:54Z yegor256@yahoo.com $
 * @author netcoderpl@gmail.com
 * @category phpRack
-->

<p><?php echo $this->authResult->getMessage()?></p>

<form method="post">
    <?php require_once PHPRACK_PATH . '/Runner/Auth.php' ?>
    <dd>Login:<br/><input name="<?php echo phpRack_Runner_Auth::POST_LOGIN?>" /></dd>
    <dd>Password:<br/><input name="<?php echo phpRack_Runner_Auth::POST_PWD?>" type="password" /></dd>
    <dd><input type="submit" /></dd>
</form>
